In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
file_path = '/content/drive/MyDrive/Minor-Project/ERC-EFR/Codebase/MaSaC_val_erc.json'

In [3]:
import pandas as pd
test1 = pd.read_json(file_path)
df = pd.DataFrame(test1)
df

,episode,speakers,utterances,emotions
0,roseshantstobeadopted.wmv,"[good rosesh, bad rosesh, good rosesh, bad ros...",[ye kya kar raha hai rosesh? bharat tera desh!...,"[neutral, neutral, neutral, contempt, neutral,..."
1,video1.wmv,"[kismi, rosesh, kismi, rosesh, kismi, rosesh, ...","[excuse me, kaun hai kaun hai?, mai kismi, kis...","[neutral, fear, neutral, neutral, neutral, joy..."
2,yamraj.wmv,"[rosesh, maya, rosesh, maya, yamraj, maya, yam...",[oh my god yamraj uncle. mama aap night gown m...,"[surprise, fear, sadness, anger, contempt, sad..."
3,finale.avi,"[sahil, monisha, rosesh, maya, rosesh, indrava...",[mr. sindolin ghar mein matlab hamare parivar ...,"[contempt, neutral, neutral, neutral, neutral,..."
4,finale.avi,"[vithal, sahil, maya, monisha, monisha, indrav...",[sahil baba bete honi ko kaun tal sakta hai. b...,"[neutral, sadness, fear, sadness, joy, neutral..."
5,indravadanmissing.avi,"[monisha, maya, monisha, maya, rosesh, sahil, ...","[ mamee jee, sandwichh?, nahin, nahin, nahin....","[neutral, sadness, neutral, neutral, neutral, ..."
6,sharman.wmw,"[indravardhan, sharman, indravardhan, rosesh, ...","[fir to tumhen 100% jail hogi sharman, it's pr...","[neutral, contempt, neutral, joy, neutral, neu..."
7,soniyaprediction.avi,"[sahil, monisha, maya, sahil, indravardhan, du...","[manisha tum theek to ho, mummy ji theek hai?,...","[fear, neutral, neutral, fear, neutral, neutra..."
8,bachelor.wmv,"[monisha, maya, monisha, maya, monisha, maya, ...","[keya bigara hai maine tera? haa, mera table. ...","[anger, sadness, anger, disgust, anger, fear, ..."
9,cricket.wmv,"[rosesh, maya, rosesh, maya, rosesh, maya, ros...","[okay momma, ish clue ke hisaab se iye , roses...","[neutral, contempt, sadness, contempt, neutral..."
10,husbandsdonotcheat.avi,"[sahil, monisha , sahil, monisha ]",[darling hamare ghar me mirchi ka anchar nehi ...,"[neutral, neutral, neutral, sadness]"
11,introductiontothesarabhaifamily.avi,"[maya, sahil, maya, sahil, maya, sahil, maya, ...","[sahil. monisha hain ghar mein?, na nahi mom.,...","[joy, joy, sadness, neutral, disgust, neutral,..."
12,jugalkishore.wmv,"[jugalkishore, monisha, jugalkishore, monisha,...",[yaha rehkar mein usse dur nahi reh payoonga m...,"[sadness, anger, sadness, anger, fear, sadness..."
13,lease1.wmv,"[sonya, maya , rosheh, maya , rosheh, maya , s...","[mom, guru saaf saaf bata raha hain ki lease k...","[surprise, fear, fear, fear, fear, fear, neutr..."
14,lease2.wmv,"[monisha , indu, rosesh, indu, monisha , indu,...",[bakura bakura iye sab keya ho raha hain? baku...,"[anger, joy, fear, neutral, neutral, joy, fear..."
15,mayaleavesindravardhan(1) (1).wmv,"[maya, sudhanshu, indravardhan, sudhanshu, may...","[hello sudhanshu, flower for my darling maya, ...","[joy, joy, neutral, joy, joy, neutral, neutral..."
16,mayadoubtsindravardhan.wmv,"[sahil, roshesh, maya, sahil, maya, roshesh, m...",[all set dad..great dekhiye mai aapko missed c...,"[joy, sadness, anger, joy, neutral, sadness, n..."
17,jaspal.wmv,"[maya, rosesh, maya, rosesh, maya, rosesh, may...","[i can't take it! i just can't take it!, aapne...","[anger, sadness, sadness, neutral, contempt, n..."
18,mayabetmonisha.wmv,"[sahil, monisha, sahil, monisha, sahil, monish...","[umm, monu, khana tumne banaya hai?, kyun puch...","[neutral, neutral, neutral, anger, joy, surpri..."
19,mayaleavesindravardhan.wmv,"[indravadhan, maya, indravadhan, maya, indrava...",[maya..hah..maya..haha..jogging karke aaya..aa...,"[joy, fear, joy, fear, neutral, anger, neutral..."
20,mayamonishabday.avi,"[roshesh, indravardhan, maya, roshesh, indrava...",[agar kal mera puna me show nhi rahta to mai t...,"[joy, contempt, joy, joy, neutral, joy, neutra..."
21,mayanighmare,"[rosesh, maya, rosesh, maya, rosesh, maya, ros...","[momma, sahil bhai ka phone aaya tha, wo aapko...","[fear, fear, neutral, contempt, neutral, neutr..."
22,mayaonacleaningdrive.wmv,"[sahil, indravardhan, sahil, indravardhan, may...","[mom,mom, maya maya tumhari umar hi kya thi, c...","[neutral, sadness, anger, sadness, neutral, ne..."
23,monishaadaptstohighsociety,"[maya, monisha, maya, monisha, rosesh, maya, m...","[this is just not done monisha, just not done,...","[anger, neutral, anger, neutral, neutral, ange..."
24,roseshnayadon.wmv,"[raj gopal sharma, rosesh, rosesh, raj gopal s...","[rosesh ready for the shot?, yeah yeah, sahil ...","[neutral, neutral, neutral, fear, anger, neutr..."
25,roseshmarriesrita.wmw,"[maya, monisha, indravadan, sahil, indravadan,...",[haan sarita bataya main usse are rosesh to aj...,"[joy, neutral, joy, neutral, joy, contempt, ne..."
26,roseshpoetrypublication.wmv,"[indravadan, monisha, indravadan, sahil, maya,...",[arey bhai vithal arey meine jo jhute khareede...,"[neutral, surprise, contempt, contempt, anger,..."
27,sahillovestory.wmv,"[sahil, rosesh, sahil, rosesh, sahil, rosesh, ...",[mom aap aa rahi haina! so come fast i am wait...,"[neutral, neutral, contempt, neutral, neutral,..."
28,sahilmarriesmonisha.wmv,"[indravadan, sahil, indravadan, monisha, indra...",[haan toh bilkul sahi kaha priya ne tu monisha...,"[neutral, contempt, neutral, neutral, neutral,..."
29,baldev,"[maya, indravardhan, maya, indravardhan, maya,...","[hello indravardhan kaise ho tum, kaam ki baat...","[neutral, neutral, contempt, neutral, neutral,..."
30,dushyant,"[indravardhan, madhusudan, indravardhan, madhu...",[to is baat ko lekar to dushyant se to tumhara...,"[joy, neutral, neutral, neutral, anger, neutra..."
31,election,"[sahil, rosesh, maya, rosesh, mrs. sanghavi, m...","[my vote goes to maya sarabhai., yay! woopie!,...","[neutral, joy, joy, joy, joy, joy, neutral, ne..."
32,election,"[mrs. sanghavi, monisha, maya, rosesh, indrava...","[oh my god! it's a tie!, tie!?, tie!?, tie!?,...","[joy, surprise, surprise, surprise, anger, sad..."
33,playatcharityfunction,"[rosesh, monisha, rosesh, sahil, indu, monisha...","[everybody, pay attention. sahil bhai, monisha...","[neutral, neutral, neutral, neutral, anger, jo..."
34,roseshaccident,"[monisha, maya, monisha, maya, rosesh, sahil, ...",[compensation! acchi baat hai kya kimat lagai ...,"[anger, neutral, anger, neutral, neutral, neut..."
35,african,"[sahil, monisha, sahil, monisha, sahil, monish...","[hi monisha, hi sahil, maine tumse kitni bar k...","[neutral, neutral, neutral, fear, joy, neutral..."
36,bachlorparty,"[maya, maya, maya, indravardhan, dushyant, mon...","[ohh... ye malvika ki vajaha re sab ga.... , h...","[sadness, joy, surprise, neutral, neutral, joy..."
37,doggy,"[monisha, maya, monisha, rosesh, maya, baldev,...","[mummy ji, jaldi!, ye... bartan andar rakho ki...","[neutral, neutral, neutral, neutral, joy, neut..."
38,monishacomplainsofsahil.wmv,"[sahil, rosesh, sahil]",[konsi cd di hai mom ne. ismein loud music baa...,"[anger, joy, surprise]"
39,monishasspeechonmaya.wmv,"[monisha, sahil, monisha]",[namaste main monisha sahil sarabhai apni sas ...,"[neutral, neutral, joy]"
40,monishasuicideattempt.wmv,"[indravardhan, maya, indravardhan, maya, indra...","[good morning maya, good morning sweetie, nash...","[neutral, joy, neutral, neutral, sadness, neut..."
41,neelimaverma.wmv,"[neelima, sahil, neelima, monisha, neelima, mo...",[i am really really really very sorry doctor s...,"[neutral, disgust, neutral, surprise, fear, ne..."
42,newcar,"[monisha, indu, monisha, indu, monisha, indu, ...",[sahil ko pta chalega to kya hoga daddy ji? mu...,"[fear, neutral, sadness, surprise, fear, anger..."
43,patang,"[sahil, monisha, sahil, monisha, sahil, monish...","[monisha, mere joote. oh my god., sahil, ye rh...","[surprise, neutral, neutral, joy, joy, joy, ne..."
44,popatlal,"[rosesh, maya, rosesh, maya, rosesh, maya, ros...","[momma!, rosesh, hausla rakho, sweetie, kaise ...","[sadness, neutral, sadness, neutral, sadness, ..."
45,prefinale,"[monish, sahil, monish, sahil, monish]",[sahil sahil sahil. sirf 4 din bache hai or sa...,"[fear, neutral, sadness, neutral, fear]"

In [4]:
len(df['speakers'][1])

44

In [5]:
newValDF = pd.DataFrame(columns = ['episode', 'speakers', 'utterances', 'emotions'])

for col in ['speakers', 'utterances', 'emotions']:
    i=0
    for row in range(len(df)):
        tempList = df.iloc[row][col]
        episodeName = df.iloc[row]['episode']
        for e in tempList:
            newValDF.at[i, col] = e
            newValDF.at[i, 'episode'] = episodeName
            i = i + 1

In [6]:
newValDF

,episode,speakers,utterances,emotions
0,roseshantstobeadopted.wmv,good rosesh,ye kya kar raha hai rosesh? bharat tera desh! ...,neutral
1,roseshantstobeadopted.wmv,bad rosesh,hahaha khat padh le rosesh baby or padhne de h...,neutral
2,roseshantstobeadopted.wmv,good rosesh,kavita acchi hai lekin khayal achcha nahin hai...,neutral
3,roseshantstobeadopted.wmv,bad rosesh,"galat hai, par momma ne tumse kaha tha ki do b...",contempt
4,roseshantstobeadopted.wmv,good rosesh,galat tha per,neutral
...,...,...,...,...
1349,prefinale,monish,sahil sahil sahil. sirf 4 din bache hai or sar...,fear
1350,prefinale,sahil,haan lekin mom unn charo me se kisi ek ko fina...,neutral
1351,prefinale,monish,mummy ji ko to unme se koi pasand nhi hai,sadness
1352,prefinale,sahil,rosesh ko?,neutral
1353,prefinale,monish,"unhe to charo pasand hai. wese sahil, waqt bee...",fear

In [7]:
newValDF.to_csv("/content/drive/MyDrive/Minor-Project/ERC-EFR/Codebase/task1ValInput.csv", index=False)

In [8]:
task1ValCSV = pd.read_csv("/content/drive/MyDrive/Minor-Project/ERC-EFR/Codebase/task1ValInput.csv")
task1ValDF = pd.DataFrame(task1ValCSV)
task1ValDF

,episode,speakers,utterances,emotions
0,roseshantstobeadopted.wmv,good rosesh,ye kya kar raha hai rosesh? bharat tera desh! ...,neutral
1,roseshantstobeadopted.wmv,bad rosesh,hahaha khat padh le rosesh baby or padhne de h...,neutral
2,roseshantstobeadopted.wmv,good rosesh,kavita acchi hai lekin khayal achcha nahin hai...,neutral
3,roseshantstobeadopted.wmv,bad rosesh,"galat hai, par momma ne tumse kaha tha ki do b...",contempt
4,roseshantstobeadopted.wmv,good rosesh,galat tha per,neutral
...,...,...,...,...
1349,prefinale,monish,sahil sahil sahil. sirf 4 din bache hai or sar...,fear
1350,prefinale,sahil,haan lekin mom unn charo me se kisi ek ko fina...,neutral
1351,prefinale,monish,mummy ji ko to unme se koi pasand nhi hai,sadness
1352,prefinale,sahil,rosesh ko?,neutral
1353,prefinale,monish,"unhe to charo pasand hai. wese sahil, waqt bee...",fear

In [9]:
task1ValDF.columns

Index(['episode', 'speakers', 'utterances', 'emotions'], dtype='object')